version: 2

sources:
  - name: gz_raw_data

    tables:
      - name: raw_gz_sales 
        description: "sales of Greenweez / we have on row per product_id found in each orders_id"
        columns:
          - name: date_date
            description: date of purchase
            
        loaded_at_field: "CAST(date_date AS TIMESTAMP)"
        freshness:
          warn_after: {count: 90, period: day }
        
        columns:
           - name: date_date
             description: date of purchase     

      - name: raw_gz_product
        description: "products of Greenweez"
        columns:
          - name: products_id
            tests:
              - unique
              - not_null

      - name: raw_gz_ship
        description: "ship of Greenweez"
        columns:
          - name: orders_id
            tests:
              - unique
              - not_null


models:
  - name: int_orders_margin
    description: "USELESS"
    columns:
      - name: orders_id
        tests:
          - unique
          - not_null
      - name: revenue
        tests:
          - not_null

